# Generated by Django 3.1 on 2020-09-02 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_landing', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
