# Generated by Django 3.1 on 2020-09-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_auto_20200902_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='landing',
            name='returned',
            field=models.BooleanField(),
        ),
    ]
