# Generated by Django 3.1 on 2020-09-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_book_cover'),
        ('customers', '0004_auto_20200902_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_landing', to='books.book'),
        ),
    ]
