# Generated by Django 3.1 on 2020-09-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20200902_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landing',
            name='returned',
            field=models.BooleanField(default=False),
        ),
    ]
