# Generated by Django 3.1 on 2020-08-31 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_author_author_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_age',
        ),
    ]
