# Generated by Django 3.1 on 2020-08-31 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_authors',
            new_name='book_author',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_description',
            field=models.TextField(max_length=600),
        ),
    ]
